default:
  image: docker
  services:
    - docker:dind
  before_script:
    - docker info

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - deploy

build and push:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

.deploy_script: &deploy_script
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh-add <(echo "$KEY")
    - ssh -o StrictHostKeyChecking=no ${USER}@${SERVER} "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -o StrictHostKeyChecking=no ${USER}@${SERVER} "docker pull $IMAGE_TAG"
    - ssh -o StrictHostKeyChecking=no ${USER}@${SERVER} "docker stop $CONATAINER_NAME || true"
    - ssh -o StrictHostKeyChecking=no ${USER}@${SERVER} "docker rm $CONATAINER_NAME || true"
    - >
        ssh -o StrictHostKeyChecking=no ${USER}@${SERVER} "docker run -d --restart always 
        --network=host 
        -e MISTER_LISTER_SQLITE_DB=$SQLITE_DB 
        -e MISTER_LISTER_TOKEN=$TOKEN 
        --volume /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro 
        --volume $VOLUME:/data:rw 
        --name $CONATAINER_NAME $IMAGE_TAG"


deploy test:
  stage: deploy
  variables:
    KEY: $TEST_SSH_PRIVATE_KEY
    USER: $TEST_DEPLOY_USER
    SERVER: $TEST_DEPLOY_SERVER
    SQLITE_DB: $TEST_MISTER_LISTER_SQLITE_DB
    TOKEN: $TEST_MISTER_LISTER_TOKEN
    VOLUME: /opt/TEST_${CI_PROJECT_NAME}
    CONATAINER_NAME: TEST_${CI_PROJECT_NAME}
  <<: *deploy_script
  only:
    - dev

deploy prod:
  stage: deploy
  variables:
    KEY: $SSH_PRIVATE_KEY
    USER: $DEPLOY_USER
    SERVER: $DEPLOY_SERVER
    SQLITE_DB: $MISTER_LISTER_SQLITE_DB
    TOKEN: $MISTER_LISTER_TOKEN
    VOLUME: /opt/$CI_PROJECT_NAME
    CONATAINER_NAME: $CI_PROJECT_NAME
  <<: *deploy_script
  only:
    - main
